/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import laboratorio9.Bala;
import laboratorio9.Nave;
/**
 *
 * @author USER
 */
public class Partida1 extends javax.swing.JFrame {

    JLabel lbl_fondo;
    JLabel lbl_nave;
    JLabel lbl_enemigo;
    
    
    ArrayList<JLabel> balas = new ArrayList<>();
    Timer timer = null;
    
    Timer movimientoEnemigo;
    int enemigoSpeed = 2;
    boolean moverEnemigoDerecha = true; 
    
    ArrayList<Bala> balas2 = new ArrayList<>();
    
    
    
    Nave naveAliada;
    Nave naveEnemiga;
    Bala balaDiseñoAliada = new Bala();
    
    /**
     * Creates new form NewJFrame1
     */
    public Partida1() {
        initComponents();    
       
        // Creamos diseño de bala de la nave aliada
        balaDiseñoAliada = new Bala();
        balaDiseñoAliada.setIcon_bala("/Img/BalaAzul.png");
        // Creamos nave aliada
        naveAliada = new Nave(balaDiseñoAliada);
        naveAliada.setIcon_nave("/Img/NavePersonaje.png");
        naveAliada.recarga();
        // Creamos nave Enemiga
        naveEnemiga = new Nave(); //Sin bala por ahora
        naveEnemiga.setIcon_nave("/Img/NaveEnemiga.png");
        // Creamos fondo
        lbl_fondo = new JLabel();        
        ImageIcon icon = new javax.swing.ImageIcon(getClass()
                .getResource("/Img/FondoEspacio.png"));
        lbl_fondo.setIcon(icon);
        //Posicionamos objetos
        lbl_fondo.setBounds(0, 0, 306, 380);
        naveAliada.posicionarNave(110, 290);
        naveEnemiga.posicionarNave(110, 10);
        
        // Agregar el JLabel al JFrame        
        getContentPane().add(naveAliada.getLbl_nave());
        getContentPane().add(naveEnemiga.getLbl_nave());
        getContentPane().add(lbl_fondo);
        
        // Establecemos la capa de los labels        
        // 2- capa más al fondo, 1- capa media, 0- capa más arriba
        getContentPane().setComponentZOrder(naveAliada.getLbl_nave(), 0);
        getContentPane().setComponentZOrder(naveEnemiga.getLbl_nave(),1);
        getContentPane().setComponentZOrder(lbl_fondo, 2);
        
        // Configura el movimiento del enemigo
        movimientoEnemigo = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                moverEnemigoAleatoriamente(naveEnemiga.getLbl_nave());
            }
        });
        movimientoEnemigo.start();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if (evt.getKeyChar() == 'd' || evt.getKeyChar() == 'D') {
            naveAliada.moverDerecha();
        } else if (evt.getKeyChar() == 'a' || evt.getKeyChar() == 'A'){
            naveAliada.moverIzquierda();
        }
    }//GEN-LAST:event_formKeyTyped

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Disparar2();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partida1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partida1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partida1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partida1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Partida1().setVisible(true);
            }
        });
    }   
    
    
     public void moverEnemigoAleatoriamente(JLabel lbl_enemigo) {
        if (moverEnemigoDerecha) {
            lbl_enemigo.setLocation(lbl_enemigo.getX() + enemigoSpeed,
                    lbl_enemigo.getY());
        } else {
            lbl_enemigo.setLocation(lbl_enemigo.getX() - enemigoSpeed, 
                    lbl_enemigo.getY());
        }

        // Determinar el cambio de dirección aleatoriamente
        if (Math.random() < 0.01) {
            moverEnemigoDerecha = !moverEnemigoDerecha;
        }

        // Asegúrando de que el enemigo no salga de la pantalla
        if (lbl_enemigo.getX() < 0) {
            lbl_enemigo.setLocation(0, lbl_enemigo.getY());
            moverEnemigoDerecha = true;
        } else if (lbl_enemigo.getX() + lbl_enemigo.getWidth() > getWidth()) {
            lbl_enemigo.setLocation(getWidth() - lbl_enemigo.getWidth(),
                    lbl_enemigo.getY());
            moverEnemigoDerecha = false;
        }
    }
    
    public boolean detectaColisionBalaAEnemigo(JLabel lbl_bala, JLabel lbl_enemigo){
        if (((lbl_bala.getY() < lbl_enemigo.getY()+ 15 && 
            lbl_bala.getX() > lbl_enemigo.getX()-8) &&
            (lbl_bala.getY() < lbl_enemigo.getY()+ 15 && 
            lbl_bala.getX() < lbl_enemigo.getX()+79)) ||
            ((lbl_bala.getY() < lbl_enemigo.getY()+ 35 && 
            lbl_bala.getX() > lbl_enemigo.getX()+12)) &&
            (lbl_bala.getY() < lbl_enemigo.getY()+ 35 && 
            lbl_bala.getX() < lbl_enemigo.getX()+68) ||
            ((lbl_bala.getY() < lbl_enemigo.getY()+ 55 && 
            lbl_bala.getX() > lbl_enemigo.getX()+19)) &&
            (lbl_bala.getY() < lbl_enemigo.getY()+ 55 && 
            lbl_bala.getX() < lbl_enemigo.getX()+33) ||
            ((lbl_bala.getY() < lbl_enemigo.getY()+ 55 && 
            lbl_bala.getX() > lbl_enemigo.getX()+37)) &&
            (lbl_bala.getY() < lbl_enemigo.getY()+ 55 && 
            lbl_bala.getX() < lbl_enemigo.getX()+59) ||
            ((lbl_bala.getY() < lbl_enemigo.getY()+ 70 && 
            lbl_bala.getX() > lbl_enemigo.getX()+27)) &&
            (lbl_bala.getY() < lbl_enemigo.getY()+ 70 && 
            lbl_bala.getX() < lbl_enemigo.getX()+33) ||
            ((lbl_bala.getY() < lbl_enemigo.getY()+ 70 && 
            lbl_bala.getX() > lbl_enemigo.getX()+37)) &&
            (lbl_bala.getY() < lbl_enemigo.getY()+ 70 && 
            lbl_bala.getX() < lbl_enemigo.getX()+50) ) { return true;}
        else {return false;}
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
  
    public void Disparar2() {
        System.out.println("Disparando");
        
        //Creando Bala con la clase Bala
        
       Bala bala = naveAliada.disparar();
       
        if (bala == null) {
            naveAliada.recarga();
        }else   {


        
        getContentPane().add(bala.getLbl_bala());
        getContentPane().setComponentZOrder(bala.getLbl_bala(), 0);}
        
        

//        // Agrega la nueva bala a la lista de balas
//        balas2.add(bala);
//
//        // Crea un temporizador si no existe uno y comienza a mover las balas
//        if (timer == null) {
//            timer = new Timer(100, new ActionListener() {
//                @Override
//                public void actionPerformed(ActionEvent e) {
//                    mueveBalasArriba2();
//                }
//            });
//            timer.start();
//        }
    }
    
    public void mueveBalasArriba2() {
        for (int i = 0; i < balas2.size(); i++) {
            Bala bala = balas2.get(i);
            int y = bala.getLbl_bala().getY() - 12; // velocidad
            bala.getLbl_bala().setLocation(bala.getLbl_bala().getX(), y);
            
            eliminarBala2(bala, i, y);
        }
    }
    
    public void eliminarBala2(Bala bala, int i, int y) {
        if (y < -bala.getLbl_bala().getIcon().getIconHeight()) {
            // La bala ha salido de la pantalla, elimínala
            getContentPane().remove(bala.getLbl_bala());
            balas2.remove(i);
            System.out.println("Bala eliminada");
        } else if (detectaColisionBalaAEnemigo(bala.getLbl_bala(), 
                naveEnemiga.getLbl_nave())) {
            // Cambiar el icono de la bala
            ImageIcon iconExplosion = new ImageIcon(getClass()
                    .getResource("/Img/Explosion.png"));
            bala.getLbl_bala().setIcon(iconExplosion);

            // Generar un valor aleatorio entre 0 y 1
            double randomValue = Math.random();

            if (randomValue < 0.08) {
                // 50% de probabilidad: cambia la dirección del enemigo
                moverEnemigoDerecha = !moverEnemigoDerecha;
            }

            System.out.println("Bala colisionada");
        }
    }    
}